"""Add SignalTrace v2 fields

Revision ID: ef5d7ec39335
Revises: 2789078f8afd
Create Date: 2026-06-25 09:40:12.569186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5d7ec39335'
down_revision: Union[str, Sequence[str], None] = '2789078f8afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_targets_id'), 'watch_targets', ['id'], unique=False)
    op.add_column('content_logs', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('content_logs', sa.Column('source_platform', sa.String(), nullable=True))
    op.add_column('content_logs', sa.Column('author_handle', sa.String(), nullable=True))
    op.add_column('content_logs', sa.Column('author_url', sa.String(), nullable=True))
    op.add_column('content_logs', sa.Column('caption_text', sa.String(), nullable=True))
    op.add_column('content_logs', sa.Column('extracted_identifiers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_logs', 'extracted_identifiers')
    op.drop_column('content_logs', 'caption_text')
    op.drop_column('content_logs', 'author_url')
    op.drop_column('content_logs', 'author_handle')
    op.drop_column('content_logs', 'source_platform')
    op.drop_column('content_logs', 'risk_score')
    op.drop_index(op.f('ix_watch_targets_id'), table_name='watch_targets')
    op.drop_table('watch_targets')
    # ### end Alembic commands ###
